# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7be65d989df97fa6e31f641523da166790ac34188ce9da46bbe2921b8873c6f297943108197c835d978972d733e4268b99d35f5c1a93d373ad3930c6d435bef0

test:
  secret_key_base: 7b3838a1b150a0d7be9112eeff668d3ee473c633f95de210069c6f4058874d48f0ea24511e1737ebde3387284926147161bd30097420e90d8060740a5987b436

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
